"""Tools for the Supervisor Agent - File operations."""

from pathlib import Path
from datetime import datetime
from slugify import slugify

from .state import ResearchState


async def save_to_project_node(state: ResearchState) -> dict:
    """Save research results to the project directory.
    
    This node:
    1. Creates a .research/ directory in the target project
    2. Saves the research summary as a Markdown file
    3. Optionally updates CLAUDE.md with a reference
    """
    project_path = Path(state["target_project"])
    
    # Create .research/ directory in project
    research_dir = project_path / ".research"
    research_dir.mkdir(parents=True, exist_ok=True)
    
    # Generate filename from query
    filename_base = slugify(state["research_query"])[:50]
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filepath = research_dir / f"{timestamp}_{filename_base}.md"
    
    # Prepare content
    content = f"""# Research: {state["research_query"]}

**Generated:** {datetime.now().isoformat()}  
**Searches conducted:** {state["search_count"]}  
**Sources found:** {len(state["research_findings"])}

---

{state["final_summary"]}

---

*Generated by ClaudeBuddy Supervisor Agent*
"""
    
    # Write research file
    filepath.write_text(content, encoding="utf-8")
    
    # Optionally update CLAUDE.md
    try:
        await update_claude_md(project_path, state)
    except Exception:
        # Non-critical if this fails
        pass
    
    return {
        "saved_path": str(filepath),
        "messages": [
            {"role": "assistant", "content": f"Research saved to: {filepath}"}
        ],
    }


async def update_claude_md(project_path: Path, state: ResearchState):
    """Append research context reference to CLAUDE.md.
    
    This adds a brief note about available research without
    overwhelming the file with full content.
    """
    claude_md = project_path / "CLAUDE.md"
    
    # Create a brief reference section
    research_section = f"""

## Research Context

Recent research has been conducted on: **{state["research_query"]}**

Key findings are available in the `.research/` directory. This research includes:
- {len(state["research_findings"])} sources analyzed
- Comprehensive summary with executive overview
- Detailed analysis with citations

See `.research/` directory for full research documents.
"""
    
    if claude_md.exists():
        content = claude_md.read_text(encoding="utf-8")
        
        # Only add if not already present
        if "## Research Context" not in content:
            # Append to existing file
            claude_md.write_text(content + research_section, encoding="utf-8")
    else:
        # Create new CLAUDE.md
        new_content = f"""# Project Context

This project uses Claude Code for development assistance.
{research_section}
"""
        claude_md.write_text(new_content, encoding="utf-8")
